version: "3.7"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  dbapp:
    build: ./postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      interval: 3s
      timeout: 1s
      retries: 10

  buyerapp:
    build: ./buyer
    volumes:
      - .:/buyerapp
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - dbapp
      - redis

  sellerapp:
    build: "./seller"
    volumes:
      - .:/sellerapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - dbapp

  # sellervue:
  #   build: "./sellervue"
  #   command: >
  #     npm run serve
  #   ports:
  #     - "8080:8080"

volumes:
  dbdata:
    # external: true
